version: '3'
services:
  postgres:
    build: 
      context: .
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  healthcheck:
    build:
      context: ./src
    env_file:
      - ./.env