CREATE USER CUSTOM_USER WITH PASSWORD CUSTOM_PASSWORD;
-- GRANT CONNECT ON DATABASE POSTGRES_DB TO CUSTOM_USER;

CREATE SCHEMA POSTGRES_SCHEMA;
GRANT USAGE ON SCHEMA POSTGRES_SCHEMA TO CUSTOM_USER;

\connect POSTGRES_DB;

CREATE TABLE POSTGRES_SCHEMA.product_categories (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE POSTGRES_SCHEMA.products (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    comment TEXT,
    category_id INTEGER REFERENCES POSTGRES_SCHEMA.product_categories(id)
);

CREATE TABLE POSTGRES_SCHEMA.users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20) UNIQUE
);

CREATE TABLE POSTGRES_SCHEMA.orders (
    id SERIAL PRIMARY KEY,
    order_date TIMESTAMP DEFAULT NOW(),
    total_amount INTEGER NOT NULL,
    user_id INTEGER REFERENCES POSTGRES_SCHEMA.users(id)
);

CREATE TABLE POSTGRES_SCHEMA.order_details (
    id SERIAL PRIMARY KEY,
    quantity INTEGER NOT NULL,
    order_id INTEGER REFERENCES POSTGRES_SCHEMA.orders(id),
    product_id INTEGER REFERENCES POSTGRES_SCHEMA.products(id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA POSTGRES_SCHEMA TO CUSTOM_USER;