name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Semgrep
        uses: returntocorp/semgrep@v3
        with:
          version: latest

      - name: Run Semgrep scan
        env:
          SEMGREP_REPORTER: json
        run: semgrep ci --config=p/ci > results.json && cat results.json || true

      - name: Build Go binary
        run: |
          cd ./PracticalWork/Task7/src
          CGO_ENABLED=0 GOOS=linux go build -o main.exe

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy .env file from local path to workspace
        env:
            LOCALHOST_PROJECT_PATH: ${{ secrets.LOCALHOST_PROJECT_PATH }}
        working-directory: ./PracticalWork/Task7
        run: |
          echo "Copying .env file..."
          cp "$LOCALHOST_PROJECT_PATH/.env" .
          
          # Проверим, что файл скопировался
          pwd
          ls -la .env

      - name: Build Docker Images
        working-directory: ./PracticalWork/Task7
        run: docker compose build --pull

      - name: Start Application and DB via Docker Compose
        id: start_containers
        run: |
          cd ./PracticalWork/Task7
          echo "Starting services..."
          docker compose up -d

      - name: Wait for Services to be Ready
        run: sleep 30

      - name: Run ZAP Baseline Scan
        uses: OpenSecurity/owasp-zap-action/actions/baseline/scan@main
        with:
          target: http://localhost:8090
          accept-risk-alerts: true
          start_options: '-config api.disablekey=true'

      - name: Save and Upload ZAP Report
        run: |
          mkdir reports
          cp ZAP_*.html reports/ZAP_Report.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/ZAP_Report.html