name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        env:
          SEMGREP_REPORTER: json
        run: semgrep ci --config=p/ci > results.json && cat results.json || true

      - name: Build Go binary
        run: |
          cd ./PracticalWork/Task7/src
          CGO_ENABLED=0 GOOS=linux go build -o main.exe

      - name: Copy .env file from local path to workspace
        env:
            LOCALHOST_PROJECT_PATH: ${{ secrets.LOCALHOST_PROJECT_PATH }}
        working-directory: ./PracticalWork/Task7
        run: |
          echo "Copying .env file..."
          cp "$LOCALHOST_PROJECT_PATH/.env" .          
          ls -la .env

      - name: Build Docker Images
        working-directory: ./PracticalWork/Task7
        run: docker compose build

      - name: Start Application and DB via Docker Compose
        id: start_containers
        run: |
          cd ./PracticalWork/Task7
          echo "Starting services..."
          docker compose up -d

      - name: Wait for Services to be Ready
        run: sleep 30

      - name: Run ZAP Baseline Scan
        id: zap_scan
        run: |
          zaproxy -cmd -quickurl http://localhost:8090 -quickout "$(pwd)/results.html"

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: zap-result.html
          path: ${{ github.workspace }}/results.html 